version: '3'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
  mysql-db-test:
    image: mysql:8.0
    restart: always
    container_name: mysql-db-test
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
